### ISSUE TITLE
INserting more than one contentBox into the website

### ISSUE THREAD

**Issue by HeadStudios** [emotionLoop/contentBox#10]
Hi,
I love your contentBox - it works exactly how I would like. I've just installed it on the home page hook. 

Just curious though - is it possible to have multiple content boxes attached to multiple hooks pulling different content? 

When I go to configure the contentBox it seems to only allow me to edit one contentBox - but what if I wanted to let's say have 3 sections in different parts on the home page - all with different content from 3 different contentBoxes - is this possible with your module?

If so can you direct me on how to do this (not an expert in Prestashop) or what tool I would need to implement.

Thank you!

**Comment by BrunoBernardino** [comment]
Hi @HeadStudios, thanks for your question! @migcosta would be the person to know more about this, but I think you can create/configure a new contentBox module and download it via https://contentbox.org (click "Generate your module")

**Comment by savedario** [comment]
Just to spell it out: the module shows only ONE content box, by assigning it to the appropriate position/hook. If one wants more boxes, one needs to install the module multiple times, each with slightly different names, so that each can be positioned/hooked as needed.

**Comment by BrunoBernardino** [comment]
Thanks for the clarification here, @savedario !
