### ISSUE TITLE
Version of Prestashop 1.4 is not working

### ISSUE THREAD

**Issue by qant** [emotionLoop/contentBox#2]
In http://contentbox.org/index_old.php I see you have same zip archive like for Prestashop 1.5 because in you code i see you using a Context, but context in only in 1.5... can you fix the link or archive in your page http://contentbox.org/index_old.php

I wold like to get this module but for ps 1.4
Thanks.

**Comment by migcosta** [comment]
Hi qant, it is fixed now.
Thanks for point that out.
cheers

**Comment by qant** [comment]
Thank you for free module.
