### ISSUE TITLE
Module not showing

### ISSUE THREAD

**Issue by onerkript** [emotionLoop/contentBox#7]
Hi,

I installed the module and tried to hook it to "displayHome" but it's not showing. It only shows when I hook it to "displayFooter", which is not what I want. The contentbox content is a SEO optimized text that I only want to display on the homepage. What am I doing wrong ?

**Comment by migcosta** [comment]
Hi @onerkript,
first of sorry for the delay of this reply.
contentBox uses a single script/function to display all the hooks. If it shows the content on the displayFooter hook it means that the module is working correctly.
From my experience, that issue should be a theme/template related or related to your Prestashop installation. 
I would recommend that you switch to the default module and try to re hook the module
